definitions:
  request.ArticleAddOrUpdateRequest:
    properties:
      classification:
        type: integer
      first:
        type: string
      gmt_create:
        type: string
      id:
        type: integer
      platform:
        type: string
      second:
        type: string
      third:
        type: string
      title:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  request.ArticleQueryRequest:
    properties:
      classification:
        type: integer
      currentPage:
        type: integer
      first:
        type: string
      id:
        type: integer
      pageSize:
        type: integer
      platform:
        type: string
      second:
        type: string
      sorter:
        type: string
      third:
        type: string
      title:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  request.BookQueryRequest:
    properties:
      currentPage:
        type: integer
      first:
        type: string
      id:
        type: integer
      name:
        type: string
      pageSize:
        type: integer
      second:
        type: string
      sorter:
        type: string
      third:
        type: string
      type:
        type: string
    type: object
  request.ClassificationKey:
    properties:
      first:
        type: string
      id:
        type: integer
      second:
        type: string
      third:
        type: string
      type:
        type: string
    type: object
  request.ClassificationQueryRequest:
    properties:
      currentPage:
        type: integer
      first:
        type: string
      id:
        type: integer
      pageSize:
        type: integer
      second:
        type: string
      sorter:
        type: string
      third:
        type: string
      type:
        type: string
    type: object
  request.EventQueryRequest:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
  request.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  request.MessageAddOrUpdateRequest:
    properties:
      avatar:
        type: string
      content:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  request.MessageQueryRequest:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
  request.UserAddOrUpdateRequest:
    properties:
      avatar:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        type: integer
    type: object
  request.UserQueryRequest:
    properties:
      currentPage:
        type: integer
      id:
        type: integer
      name:
        type: string
      pageSize:
        type: integer
      role:
        type: string
      sorter:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/article:
    post:
      parameters:
      - description: 查询文章
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询文章
      tags:
      - Article
  /api/v1/article/add:
    post:
      parameters:
      - description: x新增文章
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleAddOrUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 新增文章
      tags:
      - Article
  /api/v1/article/delete/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除用户
      tags:
      - Article
  /api/v1/article/distinctPlatform:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询平台列表
      tags:
      - Article
  /api/v1/article/update/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新用户
      tags:
      - Article
  /api/v1/book:
    post:
      parameters:
      - description: 查询书籍
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.BookQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询书籍
      tags:
      - Book
  /api/v1/book/add:
    post:
      parameters:
      - description: 新增书籍
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleAddOrUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 新增书籍
      tags:
      - Book
  /api/v1/book/delete/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除用户
      tags:
      - Book
  /api/v1/book/update/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新用户
      tags:
      - Book
  /api/v1/classification:
    post:
      parameters:
      - description: 查询类别
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ClassificationQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询类别
      tags:
      - Classification
  /api/v1/classification/add:
    post:
      parameters:
      - description: 新增类别
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ClassificationKey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 新增类别
      tags:
      - Classification
  /api/v1/classification/delete/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除类别
      tags:
      - Classification
  /api/v1/classification/distinct:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询条件distinct
      tags:
      - Classification
  /api/v1/classification/update/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新类别
      tags:
      - Classification
  /api/v1/common/login:
    post:
      parameters:
      - description: 用户登录接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 用户登录
      tags:
      - Common
  /api/v1/event:
    post:
      parameters:
      - description: 查询一个用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.EventQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询用户
      tags:
      - Event
  /api/v1/message:
    post:
      parameters:
      - description: 查询留言
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.MessageQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询留言
      tags:
      - Message
  /api/v1/message/add:
    post:
      parameters:
      - description: 新增留言
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.MessageAddOrUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 新增留言
      tags:
      - User
  /api/v1/metto/random:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询箴言
      tags:
      - Metto
  /api/v1/node/update/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新用户
      tags:
      - Note
  /api/v1/note:
    post:
      parameters:
      - description: 查询文章
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询文章
      tags:
      - Note
  /api/v1/note/add:
    post:
      parameters:
      - description: x新增文章
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ArticleAddOrUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 新增文章
      tags:
      - Note
  /api/v1/note/delete/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除用户
      tags:
      - Note
  /api/v1/overview/achievement:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询成就
      tags:
      - Overview
  /api/v1/overview/activity:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询兴趣
      tags:
      - Overview
  /api/v1/overview/interest:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询兴趣
      tags:
      - Overview
  /api/v1/overview/task:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询任务
      tags:
      - Overview
  /api/v1/user:
    post:
      parameters:
      - description: 查询用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserQueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询用户
      tags:
      - User
  /api/v1/user/add:
    post:
      parameters:
      - description: 新增用户
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserAddOrUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 新增用户
      tags:
      - User
  /api/v1/user/delete/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 删除用户
      tags:
      - User
  /api/v1/user/update/{id}:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 更新用户
      tags:
      - User
swagger: "2.0"
